### ISSUE TITLE
Example for RTSP

### ISSUE THREAD

**Issue by renatomotorline** [liuchuancong/gsy_video_player#1]
What do I have to change in the example to work with RTSP URLs?
I have been able to try with HTTPS URLs but not with RTSP URLs.

Thanks.

**Comment by liuchuancong** [comment]
Get usage from this link：https://github.com/CarGuo/GSYVideoPlayer/wiki

**Comment by liuchuancong** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/QUESTION.md
