### ISSUE TITLE
Could not find com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.6.0-release-jitpack

### ISSUE THREAD

**Issue by tudosxxx** [liuchuancong/gsy_video_player#2]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.6.0-release-jitpack.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-java/v8.6.0-release-jitpack/gsyVideoPlayer-java-v8.6.0-release-jitpack.pom
       - https://repo.maven.apache.org/maven2/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-java/v8.6.0-release-jitpack/gsyVideoPlayer-java-v8.6.0-release-jitpack.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-java/v8.6.0-release-jitpack/gsyVideoPlayer-java-v8.6.0-release-jitpack.pom
       - https://jcenter.bintray.com/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-java/v8.6.0-release-jitpack/gsyVideoPlayer-java-v8.6.0-release-jitpack.pom
     Required by:
         project :app > project :gsy_video_player
   > Could not find com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.6.0-release-jitpack.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-exo2/v8.6.0-release-jitpack/GSYVideoPlayer-exo2-v8.6.0-release-jitpack.pom
       - https://repo.maven.apache.org/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-exo2/v8.6.0-release-jitpack/GSYVideoPlayer-exo2-v8.6.0-release-jitpack.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-exo2/v8.6.0-release-jitpack/GSYVideoPlayer-exo2-v8.6.0-release-jitpack.pom
       - https://jcenter.bintray.com/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-exo2/v8.6.0-release-jitpack/GSYVideoPlayer-exo2-v8.6.0-release-jitpack.pom
     Required by:
         project :app > project :gsy_video_player
   > Could not find com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:v8.6.0-release-jitpack.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v8.6.0-release-jitpack/GSYVideoPlayer-aliplay-v8.6.0-release-jitpack.pom
       - https://repo.maven.apache.org/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v8.6.0-release-jitpack/GSYVideoPlayer-aliplay-v8.6.0-release-jitpack.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v8.6.0-release-jitpack/GSYVideoPlayer-aliplay-v8.6.0-release-jitpack.pom
       - https://jcenter.bintray.com/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v8.6.0-release-jitpack/GSYVideoPlayer-aliplay-v8.6.0-release-jitpack.pom
     Required by:
         project :app > project :gsy_video_player
   > Could not find com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.6.0-release-jitpack.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.6.0-release-jitpack/gsyVideoPlayer-ex_so-v8.6.0-release-jitpack.pom
       - https://repo.maven.apache.org/maven2/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.6.0-release-jitpack/gsyVideoPlayer-ex_so-v8.6.0-release-jitpack.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.6.0-release-jitpack/gsyVideoPlayer-ex_so-v8.6.0-release-jitpack.pom
       - https://jcenter.bintray.com/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-ex_so/v8.6.0-release-jitpack/gsyVideoPlayer-ex_so-v8.6.0-release-jitpack.pom
     Required by:
         project :app > project :gsy_video_player

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by tudosxxx** [comment]
all  url  is 404

**Comment by liuchuancong** [comment]
```
allprojects {
    repositories {
		...
        maven { url 'https://jitpack.io' }
        maven { url "https://maven.aliyun.com/repository/public" }
    }
}
```
@tudosxxx
