### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by leijingxing** [liuchuancong/gsy_video_player#4]
What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:v9.0.0-release-jitpack.
     Searched in the following locations:
       - https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v9.0.0-release-jitpack/GSYVideoPlayer-aliplay-v9.0.0-release-jitpack.pom
       - https://maven.aliyun.com/repository/public/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v9.0.0-release-jitpack/GSYVideoPlayer-aliplay-v9.0.0-release-jitpack.pom
       - https://dl.google.com/dl/android/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v9.0.0-release-jitpack/GSYVideoPlayer-aliplay-v9.0.0-release-jitpack.pom
       - https://repo.maven.apache.org/maven2/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v9.0.0-release-jitpack/GSYVideoPlayer-aliplay-v9.0.0-release-jitpack.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/CarGuo/GSYVideoPlayer/GSYVideoPlayer-aliplay/v9.0.0-release-jitpack/GSYVideoPlayer-aliplay-v9.0.0-release-jitpack.pom
     Required by:
         project :app > project :gsy_video_player

**Comment by leijingxing** [comment]
链接404

**Comment by liuchuancong** [comment]
jitpack  加一下
